events {
    worker_connections 1024;  # 设置每个worker进程的最大连接数
}
http {
    include       /etc/nginx/mime.types;  # 添加这行
    default_type  application/octet-stream;
    # 定义上游服务器（Flask应用）
    upstream flask_app {
        server web:5000;  # 指向docker compose中的web服务
    }

    server {
        listen 80;  # 监听80端口
        server_name localhost;  # 服务器域名

        # 静态文件处理 - 直接由Nginx提供服务
        location /static/ {
            alias /app/static/; # 映射到容器内的静态文件目录
            expires 30d;  # 设置30天缓存过期时间
            # 添加缓存控制头
            add_header Cache-Control "public, immutable";
        }

        # 反向代理到Flask应用
        location / {
            proxy_pass http://flask_app; # 转发到上游服务器
             # 设置代理头信息
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}